version: "3"
services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mattskywalker
      - POSTGRES_DB=documents
  api:
    container_name: documents-api
    build:
      context: ./
      dockerfile: Dockerfile
    image: message-server:latest
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/documents
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mattskywalker
    links:
      - db
